# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVC_Demo_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVC_Demo_Swift
 	pod ‘Reachability’
	pod ‘MBProgressHUD’

  target 'MVC_Demo_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
